# Generated by Django 2.2.7 on 2019-12-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.CharField(blank=True, max_length=2, null=True)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Author', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Published_at', models.DateTimeField(auto_now=True)),
                ('Updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(blank=True, max_length=150, null=True)),
                ('Stock', models.PositiveIntegerField()),
                ('Price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Available', models.BooleanField(default=True)),
                ('Created_at', models.DateTimeField()),
                ('Published_at', models.DateTimeField()),
                ('Updated_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('Author_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.Author')),
                ('Book_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.Books')),
            ],
            options={
                'ordering': ['Book_name'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.Books'),
        ),
    ]
