# Generated by Django 2.2.7 on 2019-12-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
