# Generated by Django 2.2.7 on 2019-12-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20191212_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author',
            new_name='Book',
        ),
    ]
