# Generated by Django 2.2.7 on 2019-12-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20191212_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
