# Generated by Django 2.2.7 on 2019-12-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20191212_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Author_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.Author'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Book_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.Books'),
        ),
    ]
