# Generated by Django 2.2.7 on 2019-12-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_cart_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='book_quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='book_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.Products'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='bookapp.Products'),
        ),
    ]
