# Generated by Django 2.1.5 on 2020-01-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_auto_20191217_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
