# Generated by Django 2.1.7 on 2020-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_baseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='base64'),
        ),
    ]
