# Generated by Django 2.1.7 on 2020-02-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_auto_20200212_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='image',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
